name: "🐛 Bug Report"
description: "Report a reproducible bug"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please complete the form below.
  - type: input
    id: title
    attributes:
      label: "Bug Title"
      placeholder: "Brief summary of the issue"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide a list of steps to reproduce the bug"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: "Environment"
      placeholder: "OS, browser, version, etc."
